version: "3.9"

services:

  db:
    platform: linux/x86_64
    image: mysql:8
    env_file:
      - .env
    command: 
      - --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3333:3333"
    # volumes:
    #   - data:/var/lib/mysql

  app:
    build: .
    command: >
      sh -c "
            cd /code/
            sleep 5 &&
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - db
    env_file:
      - .env

# volumes:
#   data: