# Generated by Django 4.0.3 on 2022-03-11 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=45)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ApiAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_1', models.CharField(max_length=255)),
                ('adress_2', models.CharField(max_length=255)),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('formatted_address', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('last_seen', models.DateTimeField(verbose_name='date last seen')),
                ('latitude', models.CharField(max_length=255)),
                ('listed_date', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('property_type', models.CharField(max_length=255)),
                ('raw_address', models.CharField(max_length=255)),
                ('removed_date', models.DateTimeField(verbose_name='date removed')),
                ('state', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(verbose_name='date published')),
                ('service_type', models.CharField(max_length=45)),
                ('property_type', models.CharField(max_length=45)),
                ('surface', models.IntegerField()),
                ('room_count', models.IntegerField()),
                ('bedroom_count', models.IntegerField()),
                ('is_furnished', models.BooleanField()),
                ('has_balcony', models.BooleanField()),
                ('has_terrace', models.BooleanField()),
                ('has_elevator', models.BooleanField()),
                ('has_parking', models.BooleanField()),
                ('description', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('warranty_deposit', models.IntegerField()),
                ('energy_use', models.CharField(max_length=45)),
                ('street_number', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=45)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='favorites',
            field=models.ManyToManyField(to='adverts.advert'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
