# Generated by Django 4.0.3 on 2022-03-24 13:54

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_default_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiadvert',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 13, 54, 38, 840886, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date last seen'),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='removed_date',
            field=models.DateTimeField(verbose_name='date removed'),
        ),
    ]
