# Generated by Django 4.0.3 on 2022-03-24 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_date_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiadvert',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date last seen'),
        ),
    ]
