# Generated by Django 4.0.3 on 2022-03-24 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_date_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiadvert',
            name='removed_date',
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 13, 59, 16, 174217, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 13, 59, 16, 174241, tzinfo=utc), verbose_name='date last seen'),
        ),
    ]
