# Generated by Django 4.0.3 on 2022-03-25 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0009_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='pictures',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 10, 9, 21, 500079, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 10, 9, 21, 500131, tzinfo=utc), verbose_name='date last seen'),
        ),
    ]
