# Generated by Django 4.0.3 on 2022-03-25 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0010_pictures_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='bedroom_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='advert',
            name='pictures',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='room_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='advert',
            name='surface',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='advert',
            name='warranty_deposit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 13, 30, 29, 938948, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 13, 30, 29, 938997, tzinfo=utc), verbose_name='date last seen'),
        ),
    ]
