# Generated by Django 4.0.3 on 2022-03-27 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0011_picture_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='greenhouse_gas',
            field=models.CharField(default='C', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 17, 18, 51, 487249, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 17, 18, 51, 487300, tzinfo=utc), verbose_name='date last seen'),
        ),
    ]
