# Generated by Django 4.0.3 on 2022-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='pictures',
            field=models.JSONField(default=list),
        ),
    ]