# Generated by Django 4.0.3 on 2022-03-24 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_date_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiadvert',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 13, 55, 20, 549875, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='apiadvert',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 13, 55, 20, 549898, tzinfo=utc), verbose_name='date last seen'),
        ),
    ]
